# multi_source_fusion/config.yaml

# 1. 数据路径配置
data_paths:
  imu_path: "E:/learn/code/python/multi_source_fusion/data_raw/ADIS/ADIS16465.txt"
  gnss_path: "E:/learn/code/python/multi_source_fusion/data_raw/ADIS/GNSS_RTK.pos"
  odo_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/odo_3d.txt"
  map_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/truth_convert.csv"
  ground_truth_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/truth_convert.csv"
  output_path: "E:/learn/code/python/multi_source_fusion/results/"
  model_save_dir: "E:/learn/code/python/multi_source_fusion/models/"

sensor_params:
  imu:
    rate_hz: 200.0 # 必须与您的IMU数据频率一致

ant_lever: [ 0.136, -0.301, -0.184 ] # 天线杆臂(m), IMU坐标系下(前-右-下)

# 初始状态
initial_state:
  pos: [ 38.327958, 114.200612, 139.91 ] # [deg, deg, m]
  vel: [ 0.0, 0.0, 0.0 ]                 # [m/s, m/s, m/s] (北-东-下)
  att: [ 0.0, 0.0, 240.42 ]              # [deg, deg, deg] (滚转, 俯仰, 航向)
  # 以下为初始IMU误差，通常设为0
  gyrbias: [ 0, 0, 0 ]                   # [deg/h]
  accbias: [ 0, 0, 0 ]                   # [mGal]
  gyrscale: [ 0, 0, 0 ]                  # [ppm]
  accscale: [ 0, 0, 0 ]                  # [ppm]

# 初始状态标准差
initial_state_std:
  pos: [ 10.0, 10.0, 10.0 ]              # [m, m, m]
  vel: [ 0.1, 0.1, 0.1 ]                 # [m/s, m/s, m/s]
  att: [ 1.0, 1.0, 5.0 ]                 # [deg, deg, deg]
  gyrbias: [ 50, 50, 50 ]                # [deg/h]
  accbias: [ 250, 250, 250 ]             # [mGal]
  gyrscale: [ 1000, 1000, 1000 ]         # [ppm]
  accscale: [ 1000, 1000, 1000 ]         # [ppm]

# IMU噪声建模参数 (来自kf-gins.yaml)
imunoise:
  arw: [0.24, 0.24, 0.24]                # [deg/sqrt(hr)] 角度随机游走
  vrw: [0.24, 0.24, 0.24]                # [m/s/sqrt(hr)] 速度随机游走
  gbstd: [50.0, 50.0, 50.0]              # [deg/hr] 零偏不稳定性
  abstd: [250.0, 250.0, 250.0]           # [mGal]
  gsstd: [1000.0, 1000.0, 1000.0]        # [ppm] 比例因子不稳定性
  asstd: [1000.0, 1000.0, 1000.0]        # [ppm]
  corrtime: 1.0                          # [hr] 相关时间


# 4. 融合策略配置
fusion_strategy:
  # 融合模式: "math_only", "model_only", "weighted_fusion", "adaptive_fusion"
  mode: "math_only"
  # 模型权重（仅在 weighted_fusion 模式下有效）
  model_weight: 0.0
  # 自适应融合参数
  adaptive_params:
    min_model_weight: 0.0
    max_model_weight: 0.2
    uncertainty_threshold: 1.0
    adaptation_rate: 0.1

# 5. MTINN模型超参数
mtinn_hyperparams:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 200
  sequence_length: 50
  dropout_rate: 0.2

# 6. 地图匹配与反馈控制
map_matching:
  enable: false                   # 先关闭地图匹配，测试基础ESKF
  search_radius_m: 50.0
  weight_dist: 0.6
  weight_angle: 0.4

feedback_loop:
  enable: false                   # 先关闭反馈回路
  damping_factor: 0.5

# 7. 物理常数
physical_params:
  earth_rate: 7.292115e-5         # 地球自转角速率 (rad/s)
  earth_a: 6378137.0              # 地球长半轴 (m)
  earth_e2: 0.00669438            # 地球第一偏心率平方

# 8. ESKF特定参数 - 基于KF-GINS标准设置
eskf_params:
  # 是否启用IMU误差补偿
  enable_imu_compensation: true
  # 是否启用二阶科里奥利补偿
  enable_coriolis_compensation: true
  # 最大允许的姿态校正 (度)
  max_attitude_correction_deg: 50.0
  # 最大允许的速度校正 (m/s)
  max_velocity_correction: 20.0
  # 最大允许的位置校正 (m)
  max_position_correction: 200.0
  # 是否使用严格的重力模型
  use_gravity_model: true
  # 是否使用中点积分方法
  use_midpoint_integration: true

