# multi_source_fusion/config.yaml

# 1. 数据路径配置
data_paths:
  imu_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/IMU.txt"
  gnss_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/BeiDou.pos"
  odo_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/odo_3d.txt"
  map_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/truth_convert.csv"
  ground_truth_path: "E:/learn/code/python/multi_source_fusion/data_raw/deal/truth_convert.csv"
  output_path: "E:/learn/code/python/multi_source_fusion/results/"
  model_save_dir: "E:/learn/code/python/multi_source_fusion/models/"

# 2. 传感器特性参数 - 基于KF-GINS标准设置
sensor_params:
  imu:
    rate_hz: 200.0
    # 陀螺仪噪声参数 - 基于MEMS IMU典型值
    gyro_noise_std: 1.0e-4        # 角度随机游走 (rad/s)
    gyro_bias_std: 1.0e-4         # 偏置初始不确定性 (rad/s)
    gyro_bias_walk: 1.0e-6        # 偏置随机游走 (rad/s²)
    gyro_scale_std: 1.0e-3        # 比例因子初始不确定性
    # 加速度计噪声参数 - 基于MEMS IMU典型值
    accel_noise_std: 1.0e-3       # 速度随机游走 (m/s²)
    accel_bias_std: 1.0e-3        # 偏置初始不确定性 (m/s²)
    accel_bias_walk: 1.0e-5       # 偏置随机游走 (m/s³)
    accel_scale_std: 1.0e-3       # 比例因子初始不确定性
    # 其他参数
    scale_walk: 1.0e-8            # 比例因子随机游走
  gnss:
    rate_hz: 1.0
    # GNSS测量噪声标准差
    pos_std_h: 1.0                # 水平位置标准差 (m)
    pos_std_v: 2.0                # 垂直位置标准差 (m)
    vel_std_h: 0.1                # 水平速度标准差 (m/s)
    vel_std_v: 0.2                # 垂直速度标准差 (m/s)
  odo:
    enable: false                 # 是否启用里程计数据
    rate_hz: 200.0
    vel_std: 0.05                 # 速度测量标准差 (m/s)

# 3. 初始对准与状态 - 基于KF-GINS标准设置
initial_state:
  # 初始姿态 (roll, pitch, yaw) in degrees
  init_att: [0, 0, 240.42]
  # 初始姿态不确定性 (degrees) - 更保守的设置
  init_att_std: [0.5, 0.5, 1.0]
  # 初始速度 (Ve, Vn, Vu) in m/s
  init_vel: [0.0, 0.0, 0.0]
  # 初始速度不确定性 (m/s)
  init_vel_std: [0.1, 0.1, 0.1]
  # 初始位置 (lat, lon, h) in deg, deg, m
  init_pos: [38.327958000, 114.200612500, 139.910762152]
  # 初始位置不确定性 (m) - 基于GNSS精度
  init_pos_std: [2.0, 2.0, 5.0]

# 4. 融合策略配置
fusion_strategy:
  # 融合模式: "math_only", "model_only", "weighted_fusion", "adaptive_fusion"
  mode: "math_only"
  # 模型权重（仅在 weighted_fusion 模式下有效）
  model_weight: 0.0
  # 自适应融合参数
  adaptive_params:
    min_model_weight: 0.0
    max_model_weight: 0.2
    uncertainty_threshold: 1.0
    adaptation_rate: 0.1

# 5. MTINN模型超参数
mtinn_hyperparams:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 200
  sequence_length: 50
  dropout_rate: 0.2

# 6. 地图匹配与反馈控制
map_matching:
  enable: false                   # 先关闭地图匹配，测试基础ESKF
  search_radius_m: 50.0
  weight_dist: 0.6
  weight_angle: 0.4

feedback_loop:
  enable: false                   # 先关闭反馈回路
  damping_factor: 0.5

# 7. 物理常数
physical_params:
  earth_rate: 7.292115e-5         # 地球自转角速率 (rad/s)
  earth_a: 6378137.0              # 地球长半轴 (m)
  earth_e2: 0.00669438            # 地球第一偏心率平方

# 8. ESKF特定参数 - 基于KF-GINS标准设置
eskf_params:
  # 是否启用IMU误差补偿
  enable_imu_compensation: true
  # 是否启用二阶科里奥利补偿
  enable_coriolis_compensation: true
  # 最大允许的姿态校正 (度)
  max_attitude_correction_deg: 50.0
  # 最大允许的速度校正 (m/s)
  max_velocity_correction: 200.0
  # 最大允许的位置校正 (m)
  max_position_correction: 1000.0
  # 是否使用严格的重力模型
  use_gravity_model: true
  # 是否使用中点积分方法
  use_midpoint_integration: true